"""
Netra AI — Prometheus metrics module.

Each service calls register_metrics(service_name) at startup.
All services expose /metrics on their health port.

Usage:
    from backend.core.metrics import metrics, make_metrics_app

    metrics.frames_processed.labels(camera_id="cam-01").inc()
    app.mount("/metrics", make_metrics_app())
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

try:
    from prometheus_client import (
        Counter, Gauge, Histogram, CollectorRegistry,
        make_asgi_app, REGISTRY,
    )
    _HAS_PROMETHEUS = True
except ImportError:
    _HAS_PROMETHEUS = False


# ---------------------------------------------------------------------------
# Metric definitions
# ---------------------------------------------------------------------------

if _HAS_PROMETHEUS:
    # Frames ingested by mediabridge
    frames_ingested = Counter(
        "netra_frames_ingested_total",
        "Frames written to SHM ring buffer",
        ["camera_id"],
    )

    # Frames processed by inference
    frames_processed = Counter(
        "netra_frames_processed_total",
        "Frames pulled from queue and run through inference",
        ["camera_id"],
    )

    # Frames dropped (stale or queue overflow)
    frames_dropped = Counter(
        "netra_frames_dropped_total",
        "Frames dropped due to queue overflow or stale SHM slot",
        ["camera_id", "reason"],
    )

    # Inference latency
    inference_duration = Histogram(
        "netra_inference_duration_seconds",
        "End-to-end inference time per frame (detection + pose)",
        ["camera_id"],
        buckets=[0.01, 0.025, 0.05, 0.1, 0.2, 0.5, 1.0],
    )

    # Queue depth per camera
    queue_depth = Gauge(
        "netra_queue_depth",
        "Number of frame pointers waiting in Redis queue",
        ["camera_id"],
    )

    # FSM score gauge
    fsm_score = Gauge(
        "netra_fsm_score",
        "Current FSM risk score per track",
        ["camera_id", "track_id"],
    )

    # Incidents emitted
    incidents_total = Counter(
        "netra_incidents_total",
        "Total incidents generated by risk engine",
        ["camera_id", "severity"],
    )

    # Combined risk score histogram
    risk_score_hist = Histogram(
        "netra_risk_score",
        "Combined risk score distribution at incident generation",
        ["camera_id"],
        buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
    )

    # Service uptime indicator
    service_up = Gauge(
        "netra_service_up",
        "1 if service is running, 0 if down",
        ["service"],
    )

    # Alerts dispatched
    alerts_dispatched = Counter(
        "netra_alerts_dispatched_total",
        "Alert notifications sent by channel",
        ["channel"],
    )

    # Phase 8: Broadcaster FPS per camera
    broadcaster_fps = Gauge(
        "netra_broadcaster_fps",
        "Live MJPEG output FPS per camera (measured at broadcaster fan-out)",
        ["camera_id"],
    )

    # Phase 8: WebSocket client count
    ws_clients_total = Gauge(
        "netra_ws_clients_total",
        "Number of active WebSocket connections",
    )

    # Phase 8: JPEG encode latency
    encode_latency_seconds = Histogram(
        "netra_encode_latency_seconds",
        "JPEG encode time per frame in the broadcaster",
        buckets=[0.0005, 0.001, 0.002, 0.005, 0.01, 0.025, 0.05],
    )

    def make_metrics_app() -> Any:
        """Return ASGI app that serves /metrics."""
        return make_asgi_app()

else:
    # Stubs when prometheus_client not installed
    class _Noop:
        def labels(self, **_: Any) -> "_Noop":
            return self
        def inc(self, _: float = 1) -> None:
            pass
        def set(self, _: float) -> None:
            pass
        def observe(self, _: float) -> None:
            pass

    _noop = _Noop()

    frames_ingested   = _noop
    frames_processed  = _noop
    frames_dropped    = _noop
    inference_duration = _noop
    queue_depth       = _noop
    fsm_score         = _noop
    incidents_total   = _noop
    risk_score_hist   = _noop
    service_up        = _noop
    alerts_dispatched = _noop
    broadcaster_fps   = _noop
    ws_clients_total  = _noop
    encode_latency_seconds = _noop

    def make_metrics_app() -> Any:
        from fastapi import FastAPI
        app = FastAPI()

        @app.get("/metrics")
        def _() -> dict:
            return {"status": "prometheus_client not installed"}

        return app
